In [1]:
import tensorflow as tf
import keras
import numpy as np
from customlayer import MyLayerNorm

In [2]:
# Load the dataset
(X_train_all, y_train_all), (X_test, y_test) = keras.datasets.cifar10.load_data()

X_valid, y_valid = X_train_all[-5000:], y_train_all[-5000:]
X_train, y_train = X_train_all[:-5000], y_train_all[:-5000]

In [3]:
X_train = (X_train / 255.)
X_valid = (X_valid / 255.) 
X_test = (X_test / 255.)

In [5]:
X_train.shape

(45000, 32, 32, 3)

In [ ]:
X_train[0:32]

In [6]:
layernorm = tf.keras.layers.LayerNormalization(axis=[1, 2, 3])

sample1 = X_train[0:32]
norm_values1 = layernorm(sample1)

sample2 = X_train[1:2]
norm_values2 = layernorm(sample2)


print(norm_values1.shape)
print(norm_values2.shape)

print(norm_values1)

(32, 32, 32, 3)
(1, 32, 32, 3)
tf.Tensor(
[[[[-0.84507644 -0.7880374  -0.76902443]
   [-1.1492847  -1.0922457  -1.1112586 ]
   [-1.0161936  -1.0542196  -1.1492847 ]
   ...
   [ 1.0372119   0.5428735   0.0865612 ]
   [ 0.9231338   0.40978244 -0.02751688]
   [ 0.8470817   0.39076942 -0.00850387]]

  [[-1.662636   -1.586584   -1.586584  ]
   [-1.9668443  -1.9668443  -1.9668443 ]
   [-1.6246101  -1.8147402  -1.9668443 ]
   ...
   [ 0.3717564  -0.2936991  -0.9211285 ]
   [ 0.29570433 -0.38876414 -1.0161936 ]
   [ 0.3527434  -0.31271207 -0.8831025 ]]

  [[-1.491519   -1.5105319  -1.5675709 ]
   [-1.662636   -1.8337532  -1.9668443 ]
   [-1.0352066  -1.4534929  -1.8147402 ]
   ...
   [ 0.27669135 -0.36975113 -1.0161936 ]
   [ 0.31471735 -0.36975113 -1.0161936 ]
   [ 0.10557421 -0.57889426 -1.1682976 ]]

  ...

  [[ 1.9878626   1.265368   -0.14159496]
   [ 1.8547715   0.94214684 -1.3204018 ]
   [ 1.7977325   1.0942509  -1.4725059 ]
   ...
   [ 1.0752379   0.56188655 -0.63593334]
   [-0.9021155 

In [ ]:
new1 = tf.reshape(norm_values1, [-1])

In [ ]:
new2 = tf.reshape(norm_values2, [-1])

In [ ]:
diff = tf.subtract(new1, new2)

In [ ]:
mean = tf.reduce_mean(diff)

In [ ]:
print(mean)

In [ ]:
layernorm = MyLayerNorm()

sample = X_train[:1]
norm_values = layernorm(sample)

print(norm_values)

In [ ]:
print(np.mean(norm_values[0]))
print(np.std(norm_values[0]))

In [ ]:
layer = tf.keras.layers.LayerNormalization()

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[32, 32, 3]))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(100, activation="relu"))
model.add(layer)
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [ ]:
flatten = tf.keras.layers.Flatten()
hidden_layer1 = tf.keras.layers.Dense(100, activation="relu")
layernorm = tf.keras.layers.LayerNormalization()
output = tf.keras.layers.Dense(10, activation="softmax")

In [ ]:
input_ = tf.keras.layers.Input(shape=[32, 32, 3])
flattened = flatten(input_)
hidden1 = hidden_layer1(flattened)
normed = layernorm(hidden1)
outputs = output(normed)

In [ ]:
model = tf.keras.Model(inputs=[input_], outputs=[outputs])

In [ ]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

In [ ]:
model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [ ]:
history = model.fit(
        X_train, y_train, 
        epochs=10,
        validation_data=(X_valid, y_valid), 
        batch_size=128
    )

In [ ]:
print(outputs)

In [ ]:
print(layer.beta.shape)
print(layer.gamma.shape)

In [ ]:
print(layer.beta)

In [ ]:
print(layer.gamma)