In [1]:
import tensorflow as tf
import keras
import numpy as np

In [11]:
from practice import MyLayerNorm

In [48]:
random = tf.random.uniform(shape=[10, 32], minval=-10., maxval=10.)

In [52]:
one = random[:1]

In [51]:
two = random[1:2]

In [55]:
diff = tf.subtract(one, two)

In [59]:
euclid = tf.norm(diff, ord='euclidean', axis=-1)

In [62]:
euclid.numpy()[0]

44.441143

In [43]:
random.shape[0]

10

In [44]:
random

<tf.Tensor: shape=(10, 32), dtype=float32, numpy=
array([[ 7.05357   ,  6.201195  , -4.0945053 ,  0.10530281,  9.62001   ,
         1.6769266 ,  1.7386932 ,  5.92828   ,  7.9534454 , -6.9672775 ,
         5.3226395 , -6.2105417 ,  1.3196487 , -8.051977  ,  4.8744373 ,
        -7.897942  , -0.7179451 , -9.640549  ,  8.731274  , -5.184772  ,
         5.141447  , -5.227759  ,  3.9194565 , -6.809783  ,  8.105402  ,
         3.2499409 , -6.2318707 ,  6.8911    ,  4.7839117 , -9.5318365 ,
         4.926893  , -1.2772064 ],
       [-5.592947  ,  9.906727  , -4.137988  , -3.4392977 ,  6.972824  ,
         6.3664455 , -5.930567  ,  8.81538   ,  5.3288956 , -9.794882  ,
        -0.7032442 ,  4.8776836 ,  6.7857723 ,  6.7084274 , -7.2071385 ,
         1.9949036 , -5.594094  , -1.3390179 , -2.9012132 , -4.8963833 ,
        -8.695572  , -3.0579257 ,  6.4405518 , -2.5229168 , -9.951002  ,
        -3.6961985 , -5.9874988 ,  6.4512615 ,  1.241333  , -4.310529  ,
        -2.1957827 ,  9.972162  ],
    

In [33]:
3200 // 32

100

In [39]:
random[8:]

<tf.Tensor: shape=(2, 32), dtype=float32, numpy=
array([[ 9.006083  , -7.101512  ,  3.2447767 , -5.140643  ,  2.8024054 ,
        -8.987043  ,  3.6991577 , -9.358373  , -8.144336  , -2.0810485 ,
        -5.846832  ,  8.267826  , -6.991644  ,  0.28237152,  7.399891  ,
        -2.0475245 , -7.5953007 ,  0.20439625, -4.097309  ,  8.331642  ,
         5.653949  , -9.187595  ,  7.8533897 ,  3.8749123 , -4.7011185 ,
        -9.029457  , -4.3417525 ,  1.5672417 ,  1.2131481 , -1.0273342 ,
        -4.610698  ,  6.5926533 ],
       [ 9.743738  ,  6.1137505 , -1.589859  , -9.949813  , -1.0100937 ,
        -6.154499  ,  5.119093  ,  7.5091896 , -5.6058693 ,  0.11476326,
        -6.2294483 , -0.06266594,  7.3316174 ,  1.2701511 ,  7.7723293 ,
        -5.201311  , -6.5420723 ,  8.345875  ,  7.075226  , -4.4442606 ,
        -6.826811  , -5.639863  ,  1.5611601 , -4.859276  ,  2.89217   ,
         5.490692  , -0.8669281 , -0.05788612,  3.3887243 , -5.64703   ,
         2.5541687 ,  4.7748423 ]], dtyp

In [7]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])

In [8]:
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [36]:
layernorm = tf.keras.layers.LayerNormalization()

sample1 = random[:2]
norm_values1 = layernorm(sample1)
print(norm_values1)

tf.Tensor(
[[ 1.235312   -0.7129022  -1.1319166  -1.3376179  -0.7409334   1.564098
  -0.44499695  1.9792911  -0.26178288  0.16439079  1.3721704   1.1421857
  -1.2711084   1.0311399   2.0933492  -0.837353   -1.1268097   0.6604444
   0.3076956  -0.659433   -0.08999586 -0.9951668   1.2042251  -1.1766441
  -0.15273637  0.3212307   0.02901417 -0.5171333  -0.79362893 -1.2347748
   0.0359723   0.34441602]
 [ 0.35671234  0.09739529  0.69628334 -0.61842436 -1.1578885   1.3953165
   0.3696553   1.6063097   1.4161334   1.7634288  -0.53417313 -1.5714759
   0.45498592  1.4898205  -0.8071061   0.5786965   1.474912   -0.55157876
  -0.50136167 -0.5026292  -1.3426695  -0.9728093  -0.07949387 -0.42520428
   0.06280825  0.3878532  -1.665013    0.86886555 -1.3487738   0.24425918
  -1.4657539   0.28091922]], shape=(2, 32), dtype=float32)


In [47]:
layernorm2 = MyLayerNorm()

sample = rank_1_tensor
norm_values = layernorm(sample)

print(norm_values)

2026-02-28 16:08:51.536059: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [3] vs. [32]


InvalidArgumentError: Exception encountered when calling LayerNormalization.call().

{{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [32] [Op:Mul] name: 

Arguments received by LayerNormalization.call():
  • inputs=tf.Tensor(shape=(3,), dtype=float32)

In [13]:
l2_norm_1 = tf.norm(norm_values)

In [15]:
l2_norm_1.numpy()

1.7307532

In [46]:
diff = tf.subtract(norm_values1, norm_values)

2026-02-28 16:08:43.986298: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [2,32] vs. [3]


InvalidArgumentError: {{function_node __wrapped__Sub_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [2,32] vs. [3] [Op:Sub] name: 

In [40]:
l2norm = tf.norm(diff).numpy()

In [41]:
l2norm

0.0

In [45]:
abs(-1)

1